# fly.toml app configuration file generated for git-workflow on 2025-08-29T16:14:36-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'git-workflow'
primary_region = 'ewr'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[mounts]
  source = 'visualize_git_db'
  destination = '/data'

[env]
  DATABASE_PATH = '/data/git_workflow.db'
