CREATE TABLE IF NOT EXISTS logs (
    id TEXT PRIMARY KEY,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS entries (
    log_id TEXT NOT NULL,
    row_number INTEGER NOT NULL,
    command TEXT NOT NULL,
    valid INTEGER NOT NULL,
    FOREIGN KEY (log_id) REFERENCES logs (id)
);
